kernel_modules: []

systemd_user_services: []

packages:
  - neovim
  - networkmanager
  - openssh
  - ntp
  - grub
  - efibootmgr
  - zsh
  - sudo
  - fwupd
  - git
  - fzf
  - starship
  - direnv
  - udiskie
  - libappindicator-gtk3

aur_packages: []
